version: "3.8"

services:
  client:
    build:
      context: ./apps/example-app/client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    volumes:
      - ./apps/example-app/client:/app
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./apps/example-app/server
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    volumes:
      - ./apps/example-app/server:/app
    environment:
      - NODE_ENV=development
      - PORT=5000

networks:
  default:
    driver: bridge
