services:
  client:
    build:
      context: ./apps/example-app/client
      dockerfile: Dockerfile.client
    ports:
      - "2000:2000"
    volumes:
      - /c/Users/New/Desktop/docker-monorepo-boilerplate/apps/example-app/client
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./apps/example-app/server
      dockerfile: Dockerfile.server
    ports:
      - "9000:9000"
    volumes:
      - /c/Users/New/Desktop/Docker-monorepo-boilerplate/apps/example-app/server
    environment:
      - NODE_ENV=development
      - PORT=9000

networks:
  default:
    driver: bridge
