version: '3.8'

services:
  client:
    build:
      context: ./docker
      dockerfile: Dockerfile.client
    ports:
      - '3000:3000'
    volumes:
      - ./apps/client:/app
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./docker
      dockerfile: Dockerfile.server
    ports:
      - '5000:5000'
    volumes:
      - ./apps/server:/app
    environment:
      - NODE_ENV=development
      - PORT=5000

networks:
  default:
    driver: bridge